FROM python:3.11.7

RUN pip install mlflow

EXPOSE 5001

CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0", "--port", "5001"]
